{% set name = "geokit" %}
{% set version = "1.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/geokit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 31a3416e74c3db4c34c4d51b4ddc3f62877e12c16deb18741d3b375786b2c5a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-git
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest
    - pytest-cov
    - pylint
    - autopep8
    - jupyter
    - notebook
    - jupyterlab
    - pip
    - matplotlib
    - descartes
    - pandas
    - numpy <1.24
    - scipy
    - scikit-learn
    - gdal >=3.4.2,<=3.4.3
    - smopy
    - geopandas

test:
  imports:
    - geokit
    - matplotlib
    - smopy
    - osgeo
  source_files:
    - .

  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest geokit/test/

about:
  home: https://github.com/FZJ-IEK3-VSA/geokit
  summary: GeoKit is a general purpose GIS toolkit wich is particulary usefull for conducting land eligibility analysis.
  license: MIT
  license_file: MIT-LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjwin
    - shitabishmam
    - julian-belina
    - phil-fzj
