{% set name = "geokit" %}
{% set version = "1.6.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/geokit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d0241c9b57b676c7284afc8079506dd7d6f58d6797e4831041fb2f34c008b62d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64.0.0
  run:
    - python >={{ python_min }},<={{ python_max }}
    - jupyter <=1.1.1
    - descartes <=1.1.0
    - pip <=25.5
    - matplotlib <=3.10.5
    - pandas >=1.3.4,<=2.3.3
    - numpy >=1.21.6,<=2.3.2
    - scipy >=1.7.2,<=1.16.1
    - scikit-learn >=1.3.0,<=1.7.1
    - gdal 3.4.3|3.9.3|3.10
    - smopy 0.0.7|0.0.8
    - geopandas =0.11.*|=0.12.0|=0.14.4|>=1.0.0,<=1.1.1
    - psutil >=5.8.0,<=7.1.1
    - structlog <=25.4.0
    - rich <=14.1.0
    - pooch <=1.8.2
    - tqdm

test:
  imports:
    - geokit
  source_files:
    - .
  requires:
    - pytest-xdist
    - python {{ python_min }}
  commands:
    - pytest -n auto

about:
  home: https://github.com/FZJ-IEK3-VSA/geokit
  summary: GeoKit is a general purpose GIS toolkit wich is particulary usefull for conducting land eligibility analysis.
  license: MIT
  license_file: MIT-LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjwin
    - shitabishmam
    - julian-belina
    - phil-fzj
