{% set name = "geokit" %}
{% set version = "1.4.2" %}
{% set python_min = "3.9" %}
{% set python_max = "<=3.10.13 " %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/geokit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b8828c81fe4ed5765333f92c8c720c2fb66243654ab524f54f69a16c51130159

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-git
    - setuptools
  run:
    - python >={{ python_min }},<={{ python_max }}
    - pytest
    - pytest-cov
    - pylint
    - autopep8
    - jupyter
    - notebook
    - jupyterlab
    - pip
    - matplotlib <=3.9.1
    - descartes
    - pandas <=2.3
    - numpy <1.24
    - scipy <=1.15.2 
    - scikit-learn
    - gdal >=3.4.2,<=3.4.3
    - smopy <=0.0.8 
    - geopandas <=0.14.4 

test:
  imports:
    - geokit
    - matplotlib
    - smopy
    - osgeo
  source_files:
    - .

  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest geokit/test/

about:
  home: https://github.com/FZJ-IEK3-VSA/geokit
  summary: GeoKit is a general purpose GIS toolkit wich is particulary usefull for conducting land eligibility analysis.
  license: MIT
  license_file: MIT-LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjwin
    - shitabishmam
    - julian-belina
    - phil-fzj
