{% set name = "geokit" %}
{% set version = "1.6.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.10.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/geokit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d0241c9b57b676c7284afc8079506dd7d6f58d6797e4831041fb2f34c008b62d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }},<={{ python_max }}
    - matplotlib <=3.9.1
    - pandas <=2.3.1
    - numpy <=1.26.4
    - descartes <=1.1.0
    - scipy <=1.15.2
    - scikit-learn <=1.7.1
    - gdal >=3.4.2,<=3.4.3
    - smopy <=0.0.8
    - geopandas <=0.14.4
    - pooch <=1.8.2
    - structlog <=25.4.0
    - rich <=14.1.0
    - psutil <=7.0.0

test:
  imports:
    - geokit
    - matplotlib
    - smopy
    - osgeo
  source_files:
    - .
  requires:
    - pytest-xdist
    - python {{ python_min }}
  commands:
    - pytest -n auto

about:
  home: https://github.com/FZJ-IEK3-VSA/geokit
  summary: GeoKit is a general purpose GIS toolkit wich is particulary usefull for conducting land eligibility analysis.
  license: MIT
  license_file: MIT-LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjwin
    - shitabishmam
    - julian-belina
    - phil-fzj
